BEGIN;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sf text NOT NULL UNIQUE,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TYPE whitelist_status AS ENUM ('pending', 'approved', 'rejected');

CREATE TABLE minecraft_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sf text NOT NULL REFERENCES users (sf) ON DELETE CASCADE,
    uuid text NOT NULL UNIQUE,
    whitelist_status whitelist_status NOT NULL DEFAULT 'pending',

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(sf, uuid)
);

CREATE TABLE discord_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sf text NOT NULL UNIQUE REFERENCES users (sf) ON DELETE CASCADE,

    access_token text NOT NULL,
    token_type text NOT NULL,
    refresh_token text NOT NULL,
    expiry timestamp NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);

COMMIT;