// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MinecraftAccounts string
	Users             string
}{
	MinecraftAccounts: "minecraft_accounts",
	Users:             "users",
}
