// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MinecraftAccount is an object representing the database table.
type MinecraftAccount struct {
	ID              int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	SF              string    `boil:"sf" json:"sf" toml:"sf" yaml:"sf"`
	UUID            string    `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	WhitelistStatus string    `boil:"whitelist_status" json:"whitelist_status" toml:"whitelist_status" yaml:"whitelist_status"`
	CreatedAt       time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *minecraftAccountR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L minecraftAccountL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MinecraftAccountColumns = struct {
	ID              string
	SF              string
	UUID            string
	WhitelistStatus string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "id",
	SF:              "sf",
	UUID:            "uuid",
	WhitelistStatus: "whitelist_status",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var MinecraftAccountTableColumns = struct {
	ID              string
	SF              string
	UUID            string
	WhitelistStatus string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "minecraft_accounts.id",
	SF:              "minecraft_accounts.sf",
	UUID:            "minecraft_accounts.uuid",
	WhitelistStatus: "minecraft_accounts.whitelist_status",
	CreatedAt:       "minecraft_accounts.created_at",
	UpdatedAt:       "minecraft_accounts.updated_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var MinecraftAccountWhere = struct {
	ID              whereHelperint64
	SF              whereHelperstring
	UUID            whereHelperstring
	WhitelistStatus whereHelperstring
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
}{
	ID:              whereHelperint64{field: "\"minecraft_accounts\".\"id\""},
	SF:              whereHelperstring{field: "\"minecraft_accounts\".\"sf\""},
	UUID:            whereHelperstring{field: "\"minecraft_accounts\".\"uuid\""},
	WhitelistStatus: whereHelperstring{field: "\"minecraft_accounts\".\"whitelist_status\""},
	CreatedAt:       whereHelpertime_Time{field: "\"minecraft_accounts\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"minecraft_accounts\".\"updated_at\""},
}

// MinecraftAccountRels is where relationship names are stored.
var MinecraftAccountRels = struct {
	SFUser string
}{
	SFUser: "SFUser",
}

// minecraftAccountR is where relationships are stored.
type minecraftAccountR struct {
	SFUser *User `boil:"SFUser" json:"SFUser" toml:"SFUser" yaml:"SFUser"`
}

// NewStruct creates a new relationship struct
func (*minecraftAccountR) NewStruct() *minecraftAccountR {
	return &minecraftAccountR{}
}

// minecraftAccountL is where Load methods for each relationship are stored.
type minecraftAccountL struct{}

var (
	minecraftAccountAllColumns            = []string{"id", "sf", "uuid", "whitelist_status", "created_at", "updated_at"}
	minecraftAccountColumnsWithoutDefault = []string{"sf", "uuid"}
	minecraftAccountColumnsWithDefault    = []string{"id", "whitelist_status", "created_at", "updated_at"}
	minecraftAccountPrimaryKeyColumns     = []string{"id"}
)

type (
	// MinecraftAccountSlice is an alias for a slice of pointers to MinecraftAccount.
	// This should almost always be used instead of []MinecraftAccount.
	MinecraftAccountSlice []*MinecraftAccount

	minecraftAccountQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	minecraftAccountType                 = reflect.TypeOf(&MinecraftAccount{})
	minecraftAccountMapping              = queries.MakeStructMapping(minecraftAccountType)
	minecraftAccountPrimaryKeyMapping, _ = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, minecraftAccountPrimaryKeyColumns)
	minecraftAccountInsertCacheMut       sync.RWMutex
	minecraftAccountInsertCache          = make(map[string]insertCache)
	minecraftAccountUpdateCacheMut       sync.RWMutex
	minecraftAccountUpdateCache          = make(map[string]updateCache)
	minecraftAccountUpsertCacheMut       sync.RWMutex
	minecraftAccountUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single minecraftAccount record from the query.
func (q minecraftAccountQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MinecraftAccount, error) {
	o := &MinecraftAccount{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for minecraft_accounts")
	}

	return o, nil
}

// All returns all MinecraftAccount records from the query.
func (q minecraftAccountQuery) All(ctx context.Context, exec boil.ContextExecutor) (MinecraftAccountSlice, error) {
	var o []*MinecraftAccount

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MinecraftAccount slice")
	}

	return o, nil
}

// Count returns the count of all MinecraftAccount records in the query.
func (q minecraftAccountQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count minecraft_accounts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q minecraftAccountQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if minecraft_accounts exists")
	}

	return count > 0, nil
}

// SFUser pointed to by the foreign key.
func (o *MinecraftAccount) SFUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"sf\" = ?", o.SF),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// LoadSFUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (minecraftAccountL) LoadSFUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMinecraftAccount interface{}, mods queries.Applicator) error {
	var slice []*MinecraftAccount
	var object *MinecraftAccount

	if singular {
		object = maybeMinecraftAccount.(*MinecraftAccount)
	} else {
		slice = *maybeMinecraftAccount.(*[]*MinecraftAccount)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &minecraftAccountR{}
		}
		args = append(args, object.SF)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &minecraftAccountR{}
			}

			for _, a := range args {
				if a == obj.SF {
					continue Outer
				}
			}

			args = append(args, obj.SF)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.sf in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SFUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SFMinecraftAccounts = append(foreign.R.SFMinecraftAccounts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SF == foreign.SF {
				local.R.SFUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SFMinecraftAccounts = append(foreign.R.SFMinecraftAccounts, local)
				break
			}
		}
	}

	return nil
}

// SetSFUser of the minecraftAccount to the related item.
// Sets o.R.SFUser to related.
// Adds o to related.R.SFMinecraftAccounts.
func (o *MinecraftAccount) SetSFUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"minecraft_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"sf"}),
		strmangle.WhereClause("\"", "\"", 2, minecraftAccountPrimaryKeyColumns),
	)
	values := []interface{}{related.SF, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SF = related.SF
	if o.R == nil {
		o.R = &minecraftAccountR{
			SFUser: related,
		}
	} else {
		o.R.SFUser = related
	}

	if related.R == nil {
		related.R = &userR{
			SFMinecraftAccounts: MinecraftAccountSlice{o},
		}
	} else {
		related.R.SFMinecraftAccounts = append(related.R.SFMinecraftAccounts, o)
	}

	return nil
}

// MinecraftAccounts retrieves all the records using an executor.
func MinecraftAccounts(mods ...qm.QueryMod) minecraftAccountQuery {
	mods = append(mods, qm.From("\"minecraft_accounts\""))
	return minecraftAccountQuery{NewQuery(mods...)}
}

// FindMinecraftAccount retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMinecraftAccount(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MinecraftAccount, error) {
	minecraftAccountObj := &MinecraftAccount{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"minecraft_accounts\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, minecraftAccountObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from minecraft_accounts")
	}

	return minecraftAccountObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MinecraftAccount) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no minecraft_accounts provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(minecraftAccountColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	minecraftAccountInsertCacheMut.RLock()
	cache, cached := minecraftAccountInsertCache[key]
	minecraftAccountInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			minecraftAccountAllColumns,
			minecraftAccountColumnsWithDefault,
			minecraftAccountColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"minecraft_accounts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"minecraft_accounts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into minecraft_accounts")
	}

	if !cached {
		minecraftAccountInsertCacheMut.Lock()
		minecraftAccountInsertCache[key] = cache
		minecraftAccountInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MinecraftAccount.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MinecraftAccount) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	var err error
	key := makeCacheKey(columns, nil)
	minecraftAccountUpdateCacheMut.RLock()
	cache, cached := minecraftAccountUpdateCache[key]
	minecraftAccountUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			minecraftAccountAllColumns,
			minecraftAccountPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return errors.New("models: unable to update minecraft_accounts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"minecraft_accounts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, minecraftAccountPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, append(wl, minecraftAccountPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update minecraft_accounts row")
	}

	if !cached {
		minecraftAccountUpdateCacheMut.Lock()
		minecraftAccountUpdateCache[key] = cache
		minecraftAccountUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q minecraftAccountQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for minecraft_accounts")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MinecraftAccountSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), minecraftAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"minecraft_accounts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, minecraftAccountPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in minecraftAccount slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MinecraftAccount) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no minecraft_accounts provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(minecraftAccountColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	minecraftAccountUpsertCacheMut.RLock()
	cache, cached := minecraftAccountUpsertCache[key]
	minecraftAccountUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			minecraftAccountAllColumns,
			minecraftAccountColumnsWithDefault,
			minecraftAccountColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			minecraftAccountAllColumns,
			minecraftAccountPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert minecraft_accounts, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(minecraftAccountPrimaryKeyColumns))
			copy(conflict, minecraftAccountPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"minecraft_accounts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(minecraftAccountType, minecraftAccountMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert minecraft_accounts")
	}

	if !cached {
		minecraftAccountUpsertCacheMut.Lock()
		minecraftAccountUpsertCache[key] = cache
		minecraftAccountUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MinecraftAccount record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MinecraftAccount) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no MinecraftAccount provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), minecraftAccountPrimaryKeyMapping)
	sql := "DELETE FROM \"minecraft_accounts\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from minecraft_accounts")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q minecraftAccountQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no minecraftAccountQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from minecraft_accounts")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MinecraftAccountSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), minecraftAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"minecraft_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, minecraftAccountPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from minecraftAccount slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MinecraftAccount) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMinecraftAccount(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MinecraftAccountSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MinecraftAccountSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), minecraftAccountPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"minecraft_accounts\".* FROM \"minecraft_accounts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, minecraftAccountPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MinecraftAccountSlice")
	}

	*o = slice

	return nil
}

// MinecraftAccountExists checks if the MinecraftAccount row exists.
func MinecraftAccountExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"minecraft_accounts\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if minecraft_accounts exists")
	}

	return exists, nil
}
